# Generated by Django 4.2.1 on 2023-06-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('number', models.IntegerField()),
                ('service', models.CharField(max_length=100)),
                ('specialNotes', models.TextField()),
            ],
        ),
    ]
