# Generated by Django 4.2.2 on 2023-06-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_newsletter_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='services',
            field=models.CharField(choices=[('Web Designing', 'Web Designing'), ('Email Marketing', 'Email Marketing'), ('SEO', 'SEO')], default='', max_length=200),
        ),
    ]
