# Generated by Django 4.1.9 on 2023-07-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_services_newsletter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='loveFromClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
                ('clientProfession', models.CharField(max_length=200)),
                ('clientImage', models.ImageField(height_field='60px', null=True, upload_to='static/LoveFromClient/Client Image', width_field='60px')),
                ('clientMessage', models.TextField()),
            ],
        ),
    ]
