# Generated by Django 4.1.9 on 2023-07-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_lovefromclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lovefromclient',
            name='clientImage',
            field=models.ImageField(null=True, upload_to='static/LoveFromClient/Client Image'),
        ),
    ]
