# Generated by Django 4.2.3 on 2023-07-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_blogsitebackend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
