# Generated by Django 4.2.3 on 2023-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='productItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/products/productItems')),
                ('price', models.IntegerField()),
                ('productInclude', models.TextField(null=True)),
            ],
        ),
    ]
