# Generated by Django 4.2.3 on 2023-07-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_newsletter'),
        ('users', '0014_productitem'),
    ]

    operations = [
    ]
