# Generated by Django 4.0.4 on 2023-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_0013_newsletter_0014_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='', max_length=200)),
                ('colg_name', models.CharField(max_length=100)),
                ('colg_address', models.CharField(max_length=100)),
                ('qualification', models.CharField(choices=[('B.A/B.Com/BBA/B.Ed/Diploma', 'B.A/B.Com/BBA/B.Ed/Diploma'), ('BCA/B.Tech/BE/B.Sc', 'BCA/B.Tech/BE/B.Sc'), ('M.A/M.Com/MBA/MCA/M.Ed/PG Diploma/PG Program', 'M.A/M.Com/MBA/MCA/M.Ed/PG Diploma/PG Program'), ('MCA/M.Tech/M.Sc', 'MCA/M.Tech/M.Sc'), ('others', 'others')], default='', max_length=200)),
                ('spend_time', models.CharField(choices=[('lessthan2hour', 'lessthan2hour'), ('3-4hours', '3-4hours'), ('5hours', '5hours'), ('Morethan5hours', 'Morethan5hours')], default='', max_length=200)),
                ('availablity_time', models.CharField(blank=True, max_length=100)),
                ('internship_date', models.DateField()),
                ('internship_area', models.CharField(choices=[('Campaign manager', 'Campaign manager'), ('Business Development Assicoate (BDA)', 'Business Development Assicoate (BDA)'), ('Human Resource (HR)', 'Human Resource (HR)'), ('Social Media Marketing intern', 'Social Media Marketing intern'), ('Digital marketing Intern', 'Digital marketing Intern'), ('Web Developer', 'Web Developer'), ('Graphic Designer', 'Graphic Designer'), ('Campus Ambassder', 'Campus Ambassder')], default='', max_length=200)),
                ('desktop_or_not', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=200)),
                ('internship_type', models.CharField(choices=[('Internship for college credit', 'Internship for college credit'), ('Summer Internship', 'Summer Internship'), ('Non-profit Internship', 'Non-profit Internship'), ('Co-OP(Coperative Education)', 'Co-OP(Coperative Education)'), ('Externship', 'Externship'), ('Learning purpose', 'Learning purpose')], default='', max_length=200)),
                ('any_suggestion', models.TextField(blank=True)),
            ],
        ),
    ]
